import os
import pandas as pd
import streamlit as st
from dotenv import load_dotenv

from dq_pipeline.orchestrator import run_pipeline
from dq_pipeline.io_utils import read_rules_file

load_dotenv()

st.set_page_config(page_title="GenDQ360 + Denodo AI SDK", layout="wide")

tab1, tab2 = st.tabs(["DQ Pipeline", "Chatbot (Denodo Sample)"])

with tab1:
    st.title("GenDQ360 – Data Quality Dashboard (Denodo AI SDK enabled)")

    st.markdown("""
    This tab lets you upload a **data CSV** and a **rules file** to run a
    data-quality pipeline. Outputs can be downloaded and used directly in Power BI.
    If configured, a narrative summary is generated by the **Denodo AI SDK** using
    its `/answerQuestion` endpoint.
    """)

    data_file = st.file_uploader("Upload Data CSV", type=["csv"], key="data_csv")
    rules_file = st.file_uploader("Upload Rules (CSV or Excel)", type=["csv", "xls", "xlsx"], key="rules_file")

    if data_file is not None and rules_file is not None:
        st.success("Files uploaded. Click the button below to run the pipeline.")
        if st.button("Run Data Quality Pipeline"):
            with st.spinner("Running pipeline..."):
                data_df = pd.read_csv(data_file)
                rules_df = read_rules_file(rules_file)
                result = run_pipeline(data_df, rules_df)

            st.subheader("KPI Summary")
            kpi_summary = result["kpi_summary"]
            col1, col2, col3 = st.columns(3)
            col1.metric("Completeness (Before)", f"{kpi_summary['overall_completeness_before']:.1%}")
            col2.metric("Completeness (After)", f"{kpi_summary['overall_completeness_after']:.1%}")
            col3.metric("Total Violations", f"{kpi_summary['total_violations']}")

            if result["narrative"]:
                st.subheader("AI Narrative (via Denodo AI SDK)")
                st.markdown(result["narrative"])
            else:
                st.info("No AI narrative generated. Check AI_SDK_BASE_URL / credentials in .env if you want this enabled.")

            st.subheader("Column-level KPIs")
            st.dataframe(result["kpi_table"], use_container_width=True)

            st.subheader("Profiling Summary")
            st.dataframe(result["profile"], use_container_width=True)

            st.subheader("Violations")
            if result["violations"].empty:
                st.info("No violations found based on the provided rules.")
            else:
                st.dataframe(result["violations"], use_container_width=True)

            st.subheader("Cleaned Data (first 50 rows)")
            st.dataframe(result["cleaned"].head(50), use_container_width=True)

            st.subheader("Download Outputs (for Power BI)")

            def df_to_csv_bytes(df: pd.DataFrame) -> bytes:
                return df.to_csv(index=False).encode("utf-8")

            st.download_button(
                label="Download Cleaned Data (CSV)",
                data=df_to_csv_bytes(result["cleaned"]),
                file_name="cleaned_data.csv",
                mime="text/csv",
            )
            st.download_button(
                label="Download Violations (CSV)",
                data=df_to_csv_bytes(result["violations"]),
                file_name="dq_violations.csv",
                mime="text/csv",
            )
            st.download_button(
                label="Download Column KPIs (CSV)",
                data=df_to_csv_bytes(result["kpi_table"]),
                file_name="dq_kpis.csv",
                mime="text/csv",
            )
            st.download_button(
                label="Download Profile (CSV)",
                data=df_to_csv_bytes(result["profile"]),
                file_name="dq_profile.csv",
                mime="text/csv",
            )
    else:
        st.info("Please upload both a Data CSV and a Rules file.")

with tab2:
    st.title("Denodo AI SDK – Sample Chatbot")

    st.markdown("""
    This tab embeds the **official Denodo AI SDK Sample Chatbot** UI.

    To use it:
    1. Install and configure the **Denodo AI SDK**.
    2. From the AI SDK folder, run:
       ```bash
       python run.py both
       ```
       This starts both the API and the sample chatbot.
    3. Set `CHATBOT_URL` in your `.env` (default: `http://localhost:3000`).

    If everything is running, the chatbot should appear below.
    """)

    chatbot_url = os.getenv("CHATBOT_URL", "http://localhost:3000").strip()

    if chatbot_url:
        st.components.v1.iframe(chatbot_url, height=700, scrolling=True)
    else:
        st.warning("CHATBOT_URL is not set. Please configure it in your .env file.")
